<script lang="ts">
    export let whatsappNumber = ""; // no '+', digits only
        export let facebookUrl = "#";
            export let tagline = "";
                export let addressLines: string[] = [];
                    export let email = "";

                        function whatsappHref() {
                                const num = (whatsappNumber || "").replace(/[^\d]/g, "");
                                        const text = "Hi, I'd like to enquire about your services.";
                                                if (!num) return `https://wa.me/?text=${encodeURIComponent(text)}`;
                                                        return `https://wa.me/${num}?text=${encodeURIComponent(text)}`;
                                                            }
                                                            </script>

                                                            <footer>
                                                                <div class="footer">
                                                                        <div class="footer-left">
                                                                                    <img class="logo" src="/img/brand/logo.svg" alt="CTRA Group logo" />
                                                                                                <p>{tagline}</p>
                                                                                                        </div>

                                                                                                                <div class="footer-right">
                                                                                                                            <div class="social">
                                                                                                                                            <a
                                                                                                                                                                class="social-link"
                                                                                                                                                                                    href={facebookUrl}
                                                                                                                                                                                                        target="_blank"
                                                                                                                                                                                                                            rel="noreferrer"
                                                                                                                                                                                                                                                aria-label="Facebook"
                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                    <i class="fa-brands fa-facebook-f" aria-hidden="true"></i>
                                                                                                                                                                                                                                                                                                    </a>

                                                                                                                                                                                                                                                                                                                    <a
                                                                                                                                                                                                                                                                                                                                        class="social-link"
                                                                                                                                                                                                                                                                                                                                                            href={whatsappHref()}
                                                                                                                                                                                                                                                                                                                                                                                target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                    rel="noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                        aria-label="WhatsApp"
                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <i class="fa-brands fa-whatsapp" aria-hidden="true"></i>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p class="meta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {#each addressLines as line, i (i)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {line}<br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/each}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {#if email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/if}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        footer {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: var(--accent);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: var(--spacing5) 0 var(--spacing6) 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .footer {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        width: 90%;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                max-width: 1080px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin: 0 auto;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        justify-content: space-between;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gap: var(--spacing4);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flex-wrap: wrap;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                align-items: flex-start;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .footer-left,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .footer-right {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flex-direction: column;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gap: var(--spacing3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            flex: 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    min-width: 280px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .logo {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: 110px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .social {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: flex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: var(--spacing4);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    align-items: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .social-link {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    width: 40px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            height: 40px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: grid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            place-items: center;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: var(--color100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border-radius: var(--spacing2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border-bottom: solid var(--spacing1) var(--color30);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .social-link i {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    font-size: 18px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            line-height: 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .meta {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            margin: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </style>